########################################################################
#       This is everything you need to modify. Change all of it!       #
########################################################################

# The name of your awesome band.
artist_name: Cool Band

# The name of the album, set, EP, etc.
album_name: Great Album

# The set ID on soundcloud. See here: github.com/pearkes/singer#retrieving-your-set-id
soundcloud_set_id: 1234567

# Your soundcloud application API key. See here: github.com/pearkes/singer#retrieving-your-soundcloud-key
soundcloud_key: w09bjw09erbjwrbwr09bjrw32jv23jb2

# Your username on SoundCloud!
soundcloud_username: pearkes

# You can sign up for a Google Anayltics account here: http://www.google.com/analytics/
# That will let you see how many people come to your site, and where they come from.
# Pretty snazzy.
google_anayltics_key: UA-12345678-1

# The link to your background image. See here: github.com/pearkes/singer/#background-image
background_image_link: http://i.imgur.com/foo.jpg

# This intro will go on the first page.
singer_intro: |
        Hey! This is my band website. It's pretty cool, if I do say so
        myself. It's not configured yet – I still need to edit my
        _config.yml, but I will eventually, I promise!

# This outro will go on the first page below the track list.
singer_outro: |
        Thanks for listening. If you want to buy stuff from me, I'd love
        you forever. You can do that <a href="https://google.com">here.</a>.

# The font for the body. See here: github.com/pearkes/singer/#custom-fonts
body_font: Josefin Sans

# The font for headings. See here: github.com/pearkes/singer/#custom-fonts
heading_font: Dawning of a New Day

########################################################################
#        Useless Technical stuff below. Proceed with Caution!!!        #
########################################################################

markdown: redcarpet
pygments: true

